[package]
name = "stacky-wasm-interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
stacky = { path = "../../stacky" }
console_error_panic_hook = "0.1.7"

[lib]
crate-type = ["cdylib"]
